"""add highest_previous_debt metrics

Revision ID: 01ac0cadb95e
Revises: b1ac8cccc456
Create Date: 2026-04-30 09:06:42.143786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ac0cadb95e'
down_revision: Union[str, None] = 'b1ac8cccc456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applications', sa.Column('highest_previous_debt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applications', 'highest_previous_debt')
    # ### end Alembic commands ###
