"""add initial models

Revision ID: ce82501ff390
Revises: 
Create Date: 2026-04-26 19:56:30.770087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce82501ff390'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('years_in_business', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Integer(), nullable=True),
    sa.Column('fico_score', sa.Integer(), nullable=True),
    sa.Column('paynet_score', sa.Integer(), nullable=True),
    sa.Column('has_bankruptcy', sa.Boolean(), nullable=True),
    sa.Column('bankruptcy_years_ago', sa.Integer(), nullable=True),
    sa.Column('has_judgements', sa.Boolean(), nullable=True),
    sa.Column('has_repossessions', sa.Boolean(), nullable=True),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('requested_term_months', sa.Integer(), nullable=True),
    sa.Column('equipment_type', sa.String(length=100), nullable=True),
    sa.Column('equipment_age_years', sa.Integer(), nullable=True),
    sa.Column('equipment_mileage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_table('lender_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('min_loan_amount', sa.Integer(), nullable=True),
    sa.Column('max_loan_amount', sa.Integer(), nullable=True),
    sa.Column('typical_term_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('best_tier', sa.String(length=50), nullable=True),
    sa.Column('overall_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['lender_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lender_program_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('failure_reason_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['lender_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_rule_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_value', sa.String(length=100), nullable=True),
    sa.Column('expected_value', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['application_matches.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['lender_program_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_rule_results')
    op.drop_table('lender_program_rules')
    op.drop_table('application_matches')
    op.drop_table('lender_programs')
    op.drop_table('loan_applications')
    op.drop_table('lenders')
    # ### end Alembic commands ###
